### PR TITLE
fix #9

### LINKED ISSUE #9: Bug: Additional friciton on player when running into walls (falling down walls)

### PR DESCRIPTION
**Pull request by AyoubGharbi**
- Added a falling physics material ground check to fix the friction when in contact with a wall.
- 'NOTE' comments has been added!

### CODE REVIEW

**Comment by dantogno** [comment]
Hey @AyoubGharbi! 👋 

Thanks for the PR, looks like a good fix. Curious how you found this project?

**Comment by AyoubGharbi** [comment]
Hey @dantogno  :)

I was looking for a game to contribute to 😄

**Comment by Sivelos1** [comment]
Hi @AyoubGharbi 

Big thanks for the help! We just wanted to let you know that this is a small project for internal display - this isn't really going to be distributed anywhere. Also, we won't be able to change the credits for the time being, making crediting you difficult. However, if a proper credits screen is added, you've earned a spot on there.

**Comment by Sivelos1** [comment]
Just as a heads up, your help is very appreciated and fixes the bug seamlessly. We were planning on merging - so long as it's OK with you.

If you're alright with the situation, please let me know so the PR can be merged. Thanks!

**Comment by AyoubGharbi** [comment]
Hey @Sivelos1 . No worries, I'm not searching any credits, I just wanted to help! So do whatever it's needed. Moreover, you surely can merge :)

**Comment by Sivelos1** [comment]
Thanks a bunch! Your help is much appreciated. :)

**Pull request merged**
